import os

# Build the complete requirements.py file
lines = []

def add(s=""):
    lines.append(s)

add('"""Requirements Parser - Extract structured parameters from natural language."""')
add("import json, re")
add("from dataclasses import dataclass, field")
add("from enum import Enum")
add("from typing import Optional, Dict, Any, List, Tuple")
add("")
add("class ObjectCategory(str, Enum):")
add('    BOX="box"; CYLINDER="cylinder"; TUBE_SQUEEZER="tube_squeezer"; BRACKET="bracket"')
add('    ENCLOSURE="enclosure"; SPACER="spacer"; HOOK="hook"; CUP_HOLDER="cup_holder"')
add('    PHONE_STAND="phone_stand"; KEYCHAIN="keychain"; CABLE_CLIP="cable_clip"; CUSTOM="custom"')
add("")
add("class FitType(str, Enum):")
add('    TIGHT="tight"; SNUG="snug"; SLIDING="sliding"; LOOSE="loose"')
add("")
add("@dataclass")
add("class Dimension:")
add('    value: float; unit: str="mm"; context: str=""; is_target: bool=True')
add("    def to_mm(self):")
add('        c={"mm":1.0,"cm":10.0,"m":1000.0,"in":25.4,"inch":25.4,"inches":25.4,"ft":304.8}')
add("        return self.value*c.get(self.unit.lower(),1.0)")
add("")
add("@dataclass")
add("class ModelRequirements:")
add('    name: str=""; description: str=""; category: ObjectCategory=ObjectCategory.CUSTOM')
add("    target_dimensions: List[Dimension]=field(default_factory=list)")
add("    max_dimensions: Optional[Tuple[float,float,float]]=None")
add("    fit_type: FitType=FitType.SLIDING; needs_strength: bool=False")
add("    needs_flexibility: bool=False; needs_water_resistance: bool=False")
add("    wall_thickness_mm: float=2.0; corner_radius_mm: float=1.0; add_grip_texture: bool=False")
add('    reference_object: str=""; similar_to: str=""; original_text: str=""')
add("    extracted_numbers: List[float]=field(default_factory=list)")
add("    confidence_score: float=0.0; top_candidates: List[Tuple[str,float]]=field(default_factory=list)")
add("    clarification_needed: bool=False")
add("")
add("    def to_dict(self):")
add('        return {"name":self.name,"description":self.description,"category":self.category.value,')
add('                "target_dimensions":[{"value":d.value,"unit":d.unit,"context":d.context,"mm":d.to_mm()} for d in self.target_dimensions],')
add('                "max_dimensions_mm":self.max_dimensions,"fit_type":self.fit_type.value,')
add('                "needs_strength":self.needs_strength,"wall_thickness_mm":self.wall_thickness_mm,')
add('                "reference_object":self.reference_object,"similar_to":self.similar_to,')
add('                "confidence_score":self.confidence_score,"top_candidates":self.top_candidates,')
add('                "clarification_needed":self.clarification_needed}')
add("    def to_json(self, indent=2): return json.dumps(self.to_dict(), indent=indent)")
add("    def get_primary_dimension_mm(self):")
add("        return self.target_dimensions[0].to_mm() if self.target_dimensions else None")
add("")
add("@dataclass")
add("class CategoryScore:")
add("    category: ObjectCategory; raw_score: float; matched_keywords: List[str]")
add('    penalized: bool; penalty_reason: str=""')
add("")
add("class RequirementsParser:")
add('    """Parses natural language requirements using context-aware scoring."""')
add("    CONFIDENCE_THRESHOLD=5.0")
add("    DIMENSION_PATTERNS=[")
add('        r"(\\d+\\.?\\d*)\\s*(mm|cm|in|inch|inches?)\\s*(diameter|wide|tall|long|thick|deep)?",')
add('        r"(\\d+\\.?\\d*)\\s*(inches?|in|cm|mm)\\s*(wide|tall|long|thick|deep|diameter)?",')
add('        r"(diameter|width|height|length|thickness)\\s*(?:of|:|\\s)\\s*(\\d+\\.?\\d*)\\s*(mm|cm|in)?",')
add('        r"(\\d+\\.?\\d*)\\s*(oz|fl\\s*oz|ml|liter|L)\\s*(bottle|container|tube)?",')
add("    ]")
add("    CATEGORY_KEYWORDS={")
add('        ObjectCategory.TUBE_SQUEEZER:[("tube squeezer",8,True),("toothpaste squeezer",8,True),("lotion squeezer",8,True),("squeezer",4,False),("squeeze",3,False),("toothpaste",3,False),("lotion",3,False),("cream",2,False),("paste",2,False),("dispenser",2,False),("roller",2,False),("wringer",2,False)],')
add('        ObjectCategory.BRACKET:[("monitor stand",8,True),("shelf bracket",8,True),("wall mount",6,True),("corner brace",6,True),("l bracket",6,True),("l-shaped",5,True),("bracket",5,False),("mounting",3,False),("mount",2,False),("stand",1.5,False),("brace",3,False)],')
add('        ObjectCategory.ENCLOSURE:[("electronics box",8,True),("project box",8,True),("raspberry pi",7,True),("arduino",6,False),("compartment",4,False),("cavity",4,False),("enclosure",6,False),("housing",5,False),("case",3,False),("container",3,False),("hollow",4,False),("lid",3,False),("storing",3,False),("inside",2,False),("shell",3,False),("cover",2,False)],')
add('        ObjectCategory.BOX:[("rectangular prism",8,True),("calibration cube",8,True),("test cube",8,True),("solid block",6,True),("solid box",6,True),("no lid",5,True),("box",4,False)],')
add('        ObjectCategory.CYLINDER:[("cylindrical rod",7,True),("round rod",6,True),("cylinder",5,False),("rod",3,False),("peg",3,False),("disc",3,False),("disk",3,False),("pin",3,False),("shaft",3,False),("round",2,False),("tube",2,False)],')
add('        ObjectCategory.SPACER:[("spacer washer",7,True),("spacer ring",7,True),("standoff",6,False),("bushing",5,False),("grommet",5,False),("spacer",5,False),("washer",4,False),("pcb",2,False)],')
add('        ObjectCategory.HOOK:[("wall hook",7,True),("coat hook",7,True),("hook",5,False),("hanger",4,False),("clip",1.5,False),("clamp",2,False),("grip",2,False),("grabber",2,False)],')
add('        ObjectCategory.CUP_HOLDER:[("cup holder",10,True),("drink holder",8,True),("can holder",8,True),("bottle holder",7,True),("cup",4,False),("mug",4,False),("can",3,False),("beverage",3,False)],')
add('        ObjectCategory.PHONE_STAND:[("phone stand",10,True),("phone holder",8,True),("mobile stand",8,True),("smartphone stand",9,True),("cell phone stand",9,True),("phone dock",7,True),("phone cradle",7,True),("phone",3,False),("smartphone",3,False)],')
add('        ObjectCategory.KEYCHAIN:[("keychain",10,False),("key chain",10,True),("key ring",8,True),("key fob",8,True),("key tag",7,True),("key holder",7,True),("keyring",8,False),("key",2,False)],')
add('        ObjectCategory.CABLE_CLIP:[("cable clip",10,True),("cable holder",8,True),("wire clip",9,True),("cord clip",9,True),("cable organizer",7,True),("cable management",7,True),("usb clip",8,True),("cable",3,False),("wire",3,False),("cord",3,False)],')
add("    }")
add("    EXCLUSION_RULES=[")
add('        (["phone","smartphone","cell phone"],ObjectCategory.BRACKET,8),')
add('        (["cable","wire","cord","usb"],ObjectCategory.HOOK,6),')
add('        (["cup","mug","can","drink","beverage"],ObjectCategory.ENCLOSURE,5),')
add('        (["key","keychain","keyring"],ObjectCategory.HOOK,5),')
add('        (["puzzle","gear","vase"],ObjectCategory.BOX,10),')
add("    ]")
add('    STRENGTH_KEYWORDS=["strong","heavy duty","heavy-duty","robust","durable","sturdy","thick","reinforced","solid"]')
add('    FLEX_KEYWORDS=["flexible","bendy","soft","elastic","springy","snap fit"]')
add("")
add("    def __init__(self):")
add("        self._compiled_patterns=[re.compile(p,re.IGNORECASE) for p in self.DIMENSION_PATTERNS]")
add("")
add("    def parse(self, text: str) -> ModelRequirements:")
add("        requirements=ModelRequirements(original_text=text)")
add("        requirements.target_dimensions=self._extract_dimensions(text)")
add("        requirements.extracted_numbers=self._extract_all_numbers(text)")
add("        requirements.category, requirements.confidence_score, requirements.top_candidates, requirements.clarification_needed = self._classify_category(text)")
add("        requirements.needs_strength=self._check_keywords(text,self.STRENGTH_KEYWORDS)")
add("        requirements.needs_flexibility=self._check_keywords(text,self.FLEX_KEYWORDS)")
add("        requirements.fit_type=self._determine_fit_type(text)")
add("        requirements.reference_object=self._extract_reference(text)")
add("        requirements.name=self._generate_name(requirements)")
add("        requirements.description=self._generate_description(requirements)")
add("        if requirements.needs_strength: requirements.wall_thickness_mm=3.0")
add("        pd=requirements.get_primary_dimension_mm()")
add("        if pd and pd>50: requirements.wall_thickness_mm=max(requirements.wall_thickness_mm,2.5)")
add("        return requirements")
add("")
add("    def _extract_dimensions(self, text: str) -> List[Dimension]:")
add("        dimensions=[]; seen=set()")
add("        for pattern in self._compiled_patterns:")
add("            for m in pattern.finditer(text):")
add("                g=m.groups()")
add("                if len(g)>=2:")
add("                    try:")
add('                        if g[0].replace(".","").isdigit():')
add('                            v=float(g[0]); u=g[1] if len(g)>1 else "mm"; c=g[2] if len(g)>2 and g[2] else ""')
add("                        else:")
add('                            c=g[0]; v=float(g[1]); u=g[2] if len(g)>2 and g[2] else "mm"')
add("                        if v not in seen:")
add('                            seen.add(v); dimensions.append(Dimension(value=v,unit=u,context=c or ""))')
add("                    except (ValueError,IndexError): continue")
add("        return dimensions")
add("")
add("    def _extract_all_numbers(self, text: str) -> List[float]:")
